version: '2.1'
services:
  stream:
    build: .
    ports:
      - "3000:3000" # HTTP
      - "8080:8080" # HMR
    volumes:
      - ./src:/home/src
      - ./package.json:/home/package.json
      - ./package-lock.json:/home/package-lock.json
    environment:
      - "CHOKIDAR_USEPOLLING=1"
